# 加载配置文件改动时间间隔
refresh_rate: 30 seconds
appenders:
  monitor_files: #输出monitor到文件
    kind: rolling_file
    path: logs/log4rs_roll.log #日志文件位置
    append: false
    encoder:
      pattern: "{d} {l} {M} {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 50 mb #日志切割大小
      roller:
        kind: fixed_window
        pattern: "logs/log4rs_roll_{}.log" # 包含 "{}" 用于插入索引值
        base: 0 # 压缩日志索引值起点
        count: 1 # 最大保存压缩文件数

root:
  level: info #日志级别
  appenders:
    - monitor_files